Fix: Can't have write access in theme
Fatal error: Uncaught Exception: The /code/wp-content/themes/persistagency/storage/framework/cache directory must be present and writable.

Can't have write access in theme
https://pantheon.io/docs/symlinks-assumed-write-access

Solution: move storage to wp-content/uploads and make a symlink